ALTER TABLE "enderecos"
ADD FOREIGN KEY("id_cep") REFERENCES "cep"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "enderecos"
ADD FOREIGN KEY("id_estado") REFERENCES "estados"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "enderecos"
ADD FOREIGN KEY("id_cidade") REFERENCES "cidades"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "propietarios"
ADD FOREIGN KEY("id_endereco") REFERENCES "enderecos"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "casas"
ADD FOREIGN KEY("id_endereco") REFERENCES "enderecos"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "casas"
ADD FOREIGN KEY("id_propietario") REFERENCES "propietarios"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;